!function(){/*

 Copyright (C) 2013 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
(function(){function ba(g){function p(){try{M.doScroll("left")}catch(ca){q.setTimeout(p,50);return}y("poll")}function y(p){if("readystatechange"!=p.type||"complete"==A.readyState)("load"==p.type?q:A)[C](r+p.type,y,!1),!k&&(k=!0)&&g.call(q,p.type||p)}var X=A.addEventListener,k=!1,F=!0,x=X?"addEventListener":"attachEvent",C=X?"removeEventListener":"detachEvent",r=X?"":"on";if("complete"==A.readyState)g.call(q,"lazy");else{if(A.createEventObject&&M.doScroll){try{F=!q.frameElement}catch(ca){}F&&p()}A[x](r+
"DOMContentLoaded",y,!1);A[x](r+"readystatechange",y,!1);q[x](r+"load",y,!1)}}function V(){Y&&ba(function(){var g=N.length;da(g?function(){for(var p=0;p<g;++p)(function(g){q.setTimeout(function(){q.exports[N[g]].apply(q,arguments)},0)})(p)}:void 0)})}for(var q=window,A=document,M=A.documentElement,O=A.head||A.getElementsByTagName("head")[0]||M,C="",G=A.getElementsByTagName("script"),k=G.length;0<=--k;){var P=G[k],Z=P.src.match(/^[^?#]*\/run_prettify\.js(\?[^#]*)?(?:#.*)?$/);if(Z){C=Z[1]||"";P.parentNode.removeChild(P);
break}}var Y=!0,I=[],Q=[],N=[];C.replace(/[?&]([^&=]+)=([^&]+)/g,function(g,p,y){y=decodeURIComponent(y);p=decodeURIComponent(p);"autorun"==p?Y=!/^[0fn]/i.test(y):"lang"==p?I.push(y):"skin"==p?Q.push(y):"callback"==p&&N.push(y)});for(var T=q.codePrettifyLoaderBaseUrl,k=0,C=I.length;k<C;++k)(function(){var g=A.createElement("script");g.onload=g.onerror=g.onreadystatechange=function(){!g||g.readyState&&!/loaded|complete/.test(g.readyState)||(g.onerror=g.onload=g.onreadystatechange=null,--U,U||q.setTimeout(V,
0),g.parentNode&&g.parentNode.removeChild(g),g=null)};g.type="text/javascript";g.src=T+"/lang-"+encodeURIComponent(I[k])+".js";O.insertBefore(g,O.firstChild)})(I[k]);for(var U=I.length,G=[],k=0,C=Q.length;k<C;++k)G.push(T+"/skins/"+encodeURIComponent(Q[k])+".css");G.push(T+"/prettify.css");(function(g){function p(k){if(k!==y){var q=A.createElement("link");q.rel="stylesheet";q.type="text/css";k+1<y&&(q.error=q.onerror=function(){p(k+1)});q.href=g[k];O.appendChild(q)}}var y=g.length;p(0)})(G);var da=
function(){"undefined"!==typeof window&&(window.PR_SHOULD_USE_CONTINUATION=!0);var g;(function(){function p(a){function d(e){var a=e.charCodeAt(0);if(92!==a)return a;var c=e.charAt(1);return(a=k[c])?a:"0"<=c&&"7">=c?parseInt(e.substring(1),8):"u"===c||"x"===c?parseInt(e.substring(2),16):e.charCodeAt(1)}function f(e){if(32>e)return(16>e?"\\x0":"\\x")+e.toString(16);e=String.fromCharCode(e);return"\\"===e||"-"===e||"]"===e||"^"===e?"\\"+e:e}function c(e){var c=e.substring(1,e.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]",
"g"));e=[];var a="^"===c[0],b=["["];a&&b.push("^");for(var a=a?1:0,h=c.length;a<h;++a){var l=c[a];if(/\\[bdsw]/i.test(l))b.push(l);else{var l=d(l),n;a+2<h&&"-"===c[a+1]?(n=d(c[a+2]),a+=2):n=l;e.push([l,n]);65>n||122<l||(65>n||90<l||e.push([Math.max(65,l)|32,Math.min(n,90)|32]),97>n||122<l||e.push([Math.max(97,l)&-33,Math.min(n,122)&-33]))}}e.sort(function(e,a){return e[0]-a[0]||a[1]-e[1]});c=[];h=[];for(a=0;a<e.length;++a)l=e[a],l[0]<=h[1]+1?h[1]=Math.max(h[1],l[1]):c.push(h=l);for(a=0;a<c.length;++a)l=
c[a],b.push(f(l[0])),l[1]>l[0]&&(l[1]+1>l[0]&&b.push("-"),b.push(f(l[1])));b.push("]");return b.join("")}function g(e){for(var a=e.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),b=a.length,d=[],h=0,l=0;h<b;++h){var n=a[h];"("===n?++l:"\\"===n.charAt(0)&&(n=+n.substring(1))&&(n<=l?d[n]=-1:a[h]=f(n))}for(h=1;h<d.length;++h)-1===d[h]&&(d[h]=++p);for(l=h=0;h<b;++h)n=a[h],
"("===n?(++l,d[l]||(a[h]="(?:")):"\\"===n.charAt(0)&&(n=+n.substring(1))&&n<=l&&(a[h]="\\"+d[n]);for(h=0;h<b;++h)"^"===a[h]&&"^"!==a[h+1]&&(a[h]="");if(e.ignoreCase&&B)for(h=0;h<b;++h)n=a[h],e=n.charAt(0),2<=n.length&&"["===e?a[h]=c(n):"\\"!==e&&(a[h]=n.replace(/[a-zA-Z]/g,function(a){a=a.charCodeAt(0);return"["+String.fromCharCode(a&-33,a|32)+"]"}));return a.join("")}for(var p=0,B=!1,m=!1,J=0,b=a.length;J<b;++J){var t=a[J];if(t.ignoreCase)m=!0;else if(/[a-z]/i.test(t.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,
""))){B=!0;m=!1;break}}for(var k={b:8,t:9,n:10,v:11,f:12,r:13},u=[],J=0,b=a.length;J<b;++J){t=a[J];if(t.global||t.multiline)throw Error(""+t);u.push("(?:"+g(t)+")")}return new RegExp(u.join("|"),m?"gi":"g")}function q(a,d){function f(a){var b=a.nodeType;if(1==b){if(!c.test(a.className)){for(b=a.firstChild;b;b=b.nextSibling)f(b);b=a.nodeName.toLowerCase();if("br"===b||"li"===b)g[m]="\n",B[m<<1]=p++,B[m++<<1|1]=a}}else if(3==b||4==b)b=a.nodeValue,b.length&&(b=d?b.replace(/\r\n?/g,"\n"):b.replace(/[ \t\r\n]+/g,
" "),g[m]=b,B[m<<1]=p,p+=b.length,B[m++<<1|1]=a)}var c=/(?:^|\s)nocode(?:\s|$)/,g=[],p=0,B=[],m=0;f(a);return{a:g.join("").replace(/\n$/,""),c:B}}function k(a,d,f,c,g){f&&(a={h:a,l:1,j:null,m:null,a:f,c:null,i:d,g:null},c(a),g.push.apply(g,a.g))}function A(a){for(var d=void 0,f=a.firstChild;f;f=f.nextSibling)var c=f.nodeType,d=1===c?d?a:f:3===c?T.test(f.nodeValue)?a:d:d;return d===a?void 0:d}function F(a,d){function f(a){for(var m=a.i,p=a.h,b=[m,"pln"],t=0,B=a.a.match(g)||[],u={},e=0,r=B.length;e<
r;++e){var E=B[e],w=u[E],h=void 0,l;if("string"===typeof w)l=!1;else{var n=c[E.charAt(0)];if(n)h=E.match(n[1]),w=n[0];else{for(l=0;l<q;++l)if(n=d[l],h=E.match(n[1])){w=n[0];break}h||(w="pln")}!(l=5<=w.length&&"lang-"===w.substring(0,5))||h&&"string"===typeof h[1]||(l=!1,w="src");l||(u[E]=w)}n=t;t+=E.length;if(l){l=h[1];var D=E.indexOf(l),H=D+l.length;h[2]&&(H=E.length-h[2].length,D=H-l.length);w=w.substring(5);k(p,m+n,E.substring(0,D),f,b);k(p,m+n+D,l,G(w,l),b);k(p,m+n+H,E.substring(H),f,b)}else b.push(m+
n,w)}a.g=b}var c={},g;(function(){for(var f=a.concat(d),m=[],k={},b=0,t=f.length;b<t;++b){var q=f[b],u=q[3];if(u)for(var e=u.length;0<=--e;)c[u.charAt(e)]=q;q=q[1];u=""+q;k.hasOwnProperty(u)||(m.push(q),k[u]=null)}m.push(/[\0-\uffff]/);g=p(m)})();var q=d.length;return f}function x(a){var d=[],f=[];a.tripleQuotedStrings?d.push(["str",/^(?:\'\'\'(?:[^\'\\]|\\[\s\S]|\'{1,2}(?=[^\']))*(?:\'\'\'|$)|\"\"\"(?:[^\"\\]|\\[\s\S]|\"{1,2}(?=[^\"]))*(?:\"\"\"|$)|\'(?:[^\\\']|\\[\s\S])*(?:\'|$)|\"(?:[^\\\"]|\\[\s\S])*(?:\"|$))/,
null,"'\""]):a.multiLineStrings?d.push(["str",/^(?:\'(?:[^\\\']|\\[\s\S])*(?:\'|$)|\"(?:[^\\\"]|\\[\s\S])*(?:\"|$)|\`(?:[^\\\`]|\\[\s\S])*(?:\`|$))/,null,"'\"`"]):d.push(["str",/^(?:\'(?:[^\\\'\r\n]|\\.)*(?:\'|$)|\"(?:[^\\\"\r\n]|\\.)*(?:\"|$))/,null,"\"'"]);a.verbatimStrings&&f.push(["str",/^@\"(?:[^\"]|\"\")*(?:\"|$)/,null]);var c=a.hashComments;c&&(a.cStyleComments?(1<c?d.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):d.push(["com",/^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),f.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h(?:h|pp|\+\+)?|[a-z]\w*)>/,null])):d.push(["com",/^#[^\r\n]*/,null,"#"]));a.cStyleComments&&(f.push(["com",/^\/\/[^\r\n]*/,null]),f.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));if(c=a.regexLiterals){var g=(c=1<c?"":"\n\r")?".":"[\\S\\s]";f.push(["lang-regex",RegExp("^(?:^^\\.?|[+-]|[!=]=?=?|\\#|%=?|&&?=?|\\(|\\*=?|[+\\-]=|->|\\/=?|::?|<<?=?|>>?>?=?|,|;|\\?|@|\\[|~|{|\\^\\^?=?|\\|\\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\\s*("+
("/(?=[^/*"+c+"])(?:[^/\\x5B\\x5C"+c+"]|\\x5C"+g+"|\\x5B(?:[^\\x5C\\x5D"+c+"]|\\x5C"+g+")*(?:\\x5D|$))+/")+")")])}(c=a.types)&&f.push(["typ",c]);c=(""+a.keywords).replace(/^ | $/g,"");c.length&&f.push(["kwd",new RegExp("^(?:"+c.replace(/[\s,]+/g,"|")+")\\b"),null]);d.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);c="^.[^\\s\\w.$@'\"`/\\\\]*";a.regexLiterals&&(c+="(?!s*/)");f.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,
null],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,null,"0123456789"],["pln",/^\\[\s\S]?/,null],["pun",new RegExp(c),null]);return F(d,f)}function C(a,d,f){function c(a){var b=a.nodeType;if(1==b&&!p.test(a.className))if("br"===a.nodeName.toLowerCase())g(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)c(a);else if((3==b||4==b)&&f){var e=a.nodeValue,d=e.match(q);d&&(b=e.substring(0,d.index),a.nodeValue=b,(e=e.substring(d.index+
d[0].length))&&a.parentNode.insertBefore(m.createTextNode(e),a.nextSibling),g(a),b||a.parentNode.removeChild(a))}}function g(a){function c(a,b){var e=b?a.cloneNode(!1):a,n=a.parentNode;if(n){var n=c(n,1),d=a.nextSibling;n.appendChild(e);for(var f=d;f;f=d)d=f.nextSibling,n.appendChild(f)}return e}for(;!a.nextSibling;)if(a=a.parentNode,!a)return;a=c(a.nextSibling,0);for(var e;(e=a.parentNode)&&1===e.nodeType;)a=e;b.push(a)}for(var p=/(?:^|\s)nocode(?:\s|$)/,q=/\r\n?|\n/,m=a.ownerDocument,k=m.createElement("li");a.firstChild;)k.appendChild(a.firstChild);
for(var b=[k],t=0;t<b.length;++t)c(b[t]);d===(d|0)&&b[0].setAttribute("value",d);var r=m.createElement("ol");r.className="linenums";d=Math.max(0,d-1|0)||0;for(var t=0,u=b.length;t<u;++t)k=b[t],k.className="L"+(t+d)%10,k.firstChild||k.appendChild(m.createTextNode("\u00a0")),r.appendChild(k);a.appendChild(r)}function r(a,d){for(var f=d.length;0<=--f;){var c=d[f];W.hasOwnProperty(c)?R.console&&console.warn("cannot override language handler %s",c):W[c]=a}}function G(a,d){a&&W.hasOwnProperty(a)||(a=/^\s*</.test(d)?
"default-markup":"default-code");return W[a]}function I(a){var d=a.j;try{var f=q(a.h,a.l),c=f.a;a.a=c;a.c=f.c;a.i=0;G(d,c)(a);var g=/\bMSIE\s(\d+)/.exec(navigator.userAgent),g=g&&8>=+g[1],d=/\n/g,p=a.a,k=p.length,f=0,m=a.c,r=m.length,c=0,b=a.g,t=b.length,x=0;b[t]=k;var u,e;for(e=u=0;e<t;)b[e]!==b[e+2]?(b[u++]=b[e++],b[u++]=b[e++]):e+=2;t=u;for(e=u=0;e<t;){for(var y=b[e],A=b[e+1],w=e+2;w+2<=t&&b[w+1]===A;)w+=2;b[u++]=y;b[u++]=A;e=w}b.length=u;var h=a.h;a="";h&&(a=h.style.display,h.style.display="none");
try{for(;c<r;){var l=m[c+2]||k,n=b[x+2]||k,w=Math.min(l,n),D=m[c+1],H;if(1!==D.nodeType&&(H=p.substring(f,w))){g&&(H=H.replace(d,"\r"));D.nodeValue=H;var aa=D.ownerDocument,v=aa.createElement("span");v.className=b[x+1];var C=D.parentNode;C.replaceChild(v,D);v.appendChild(D);f<l&&(m[c+1]=D=aa.createTextNode(p.substring(w,l)),C.insertBefore(D,v.nextSibling))}f=w;f>=l&&(c+=2);f>=n&&(x+=2)}}finally{h&&(h.style.display=a)}}catch(z){R.console&&console.log(z&&z.stack||z)}}var R="undefined"!==typeof window?
window:{},K=["break,continue,do,else,for,if,return,while"],L=[[K,"auto,case,char,const,default,double,enum,extern,float,goto,inline,int,long,register,restrict,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],S=[L,"alignas,alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,delegate,dynamic_cast,explicit,export,friend,generic,late_check,mutable,namespace,noexcept,noreturn,nullptr,property,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],
M=[L,"abstract,assert,boolean,byte,extends,finally,final,implements,import,instanceof,interface,null,native,package,strictfp,super,synchronized,throws,transient"],N=[L,"abstract,add,alias,as,ascending,async,await,base,bool,by,byte,checked,decimal,delegate,descending,dynamic,event,finally,fixed,foreach,from,get,global,group,implicit,in,interface,internal,into,is,join,let,lock,null,object,out,override,orderby,params,partial,readonly,ref,remove,sbyte,sealed,select,set,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,value,var,virtual,where,yield"],
L=[L,"abstract,async,await,constructor,debugger,enum,eval,export,from,function,get,import,implements,instanceof,interface,let,null,of,set,undefined,var,with,yield,Infinity,NaN"],O=[K,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],P=[K,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"],
K=[K,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"],Q=/^(DIR|FILE|array|vector|(de|priority_)?queue|(forward_)?list|stack|(const_)?(reverse_)?iterator|(unordered_)?(multi)?(set|map)|bitset|u?(int|float)\d*)\b/,T=/\S/,U=x({keywords:[S,N,M,L,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",O,P,K],hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),
W={};r(U,["default-code"]);r(F([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^<\!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),"default-markup htm html mxml xhtml xml xsl".split(" "));r(F([["pln",/^[\s]+/,
null," \t\r\n"],["atv",/^(?:\"[^\"]*\"?|\'[^\']*\'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>\'\"\s]*(?:[^>\'\"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*\"([^\"]+)\"/i],["lang-js",/^on\w+\s*=\s*\'([^\']+)\'/i],["lang-js",/^on\w+\s*=\s*([^\"\'>\s]+)/i],["lang-css",/^style\s*=\s*\"([^\"]+)\"/i],["lang-css",/^style\s*=\s*\'([^\']+)\'/i],["lang-css",/^style\s*=\s*([^\"\'>\s]+)/i]]),["in.tag"]);
r(F([],[["atv",/^[\s\S]+/]]),["uq.val"]);r(x({keywords:S,hashComments:!0,cStyleComments:!0,types:Q}),"c cc cpp cxx cyc m".split(" "));r(x({keywords:"null,true,false"}),["json"]);r(x({keywords:N,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,types:Q}),["cs"]);r(x({keywords:M,cStyleComments:!0}),["java"]);r(x({keywords:K,hashComments:!0,multiLineStrings:!0}),["bash","bsh","csh","sh"]);r(x({keywords:O,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py","python"]);r(x({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",
hashComments:!0,multiLineStrings:!0,regexLiterals:2}),["perl","pl","pm"]);r(x({keywords:P,hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb","ruby"]);r(x({keywords:L,cStyleComments:!0,regexLiterals:!0}),["javascript","js","ts","typescript"]);r(x({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,
regexLiterals:!0}),["coffee"]);r(F([],[["str",/^[\s\S]+/]]),["regex"]);var V=R.PR={createSimpleLexer:F,registerLangHandler:r,sourceDecorator:x,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:function(a,d,f){f=f||!1;d=d||null;var c=document.createElement("div");c.innerHTML="<pre>"+a+"</pre>";c=c.firstChild;
f&&C(c,f,!0);I({j:d,m:f,h:c,l:1,a:null,i:null,c:null,g:null});return c.innerHTML},prettyPrint:g=function(a,d){function f(){for(var c=R.PR_SHOULD_USE_CONTINUATION?b.now()+250:Infinity;t<p.length&&b.now()<c;t++){for(var d=p[t],k=h,q=d;q=q.previousSibling;){var m=q.nodeType,v=(7===m||8===m)&&q.nodeValue;if(v?!/^\??prettify\b/.test(v):3!==m||/\S/.test(q.nodeValue))break;if(v){k={};v.replace(/\b(\w+)=([\w:.%+-]+)/g,function(a,b,c){k[b]=c});break}}q=d.className;if(!e.test(q)){m=!1;for(v=d.parentNode;v;v=
v.parentNode)if(w.test(v.tagName)&&v.className&&u.test(v.className)){m=!0;break}if(!m){d.className+=" prettyprinted";m=k.lang;if(!m){var m=q.match(r),B;!m&&(B=A(d))&&y.test(B.tagName)&&(m=B.className.match(r));m&&(m=m[1])}if(x.test(d.tagName))v=1;else var v=d.currentStyle,z=g.defaultView,v=(v=v?v.whiteSpace:z&&z.getComputedStyle?z.getComputedStyle(d,null).getPropertyValue("white-space"):0)&&"pre"===v.substring(0,3);z=k.linenums;(z="true"===z||+z)||(z=(z=q.match(/\blinenums\b(?::(\d+))?/))?z[1]&&z[1].length?
+z[1]:!0:!1);z&&C(d,z,v);I({j:m,h:d,m:z,l:v,a:null,i:null,c:null,g:null})}}}t<p.length?R.setTimeout(f,250):"function"===typeof a&&a()}for(var c=d||document.body,g=c.ownerDocument||document,c=[c.getElementsByTagName("pre"),c.getElementsByTagName("code"),c.getElementsByTagName("xmp")],p=[],k=0;k<c.length;++k)for(var m=0,q=c[k].length;m<q;++m)p.push(c[k][m]);var c=null,b=Date;b.now||(b={now:function(){return+new Date}});var t=0,r=/\blang(?:uage)?-([\w.]+)(?!\S)/,u=/\bprettyprint\b/,e=/\bprettyprinted\b/,
x=/pre|xmp/i,y=/^code$/i,w=/^(?:pre|code|xmp)$/i,h={};f()}},S=R.define;"function"===typeof S&&S.amd&&S("google-code-prettify",[],function(){return V})})();return g}();U||q.setTimeout(V,0)})();}();
